### ISSUE TITLE
استفاده در کنار Apache 

### ISSUE THREAD

**Issue by sazdahani-2001** [ErfanNamira/AriaFileServer#1]
سلام، امکانش نیس در کنار apache از aria file server استفاده کنیم؟
اگر امکانش هست تنظیمات مربوط به apche رو بهمون میگین؟!

**Comment by ErfanNamira** [comment]
درود ✨️🌺
امکان استفاده از وب‌سرور آپاچی و فایل‌سرور آریا در کنار هم هست. کافی است پورت‌های استفاده شده، متفاوت باشند.
